version: '3.4'

services:
  migrations:
    build:
      context: ../../
      dockerfile: templates/service/database/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - AuthServer_DB=WebPush_Identity
      - WebPush_DB=WebPush_ModuleDb
      - SA_PASSWORD=yourStrong(!)Password
